#!/bin/bash

if [ "$ENVIRONMENT" == "OPTIMLOL_UI_HEROKU" ] || [ "$ENVIRONMENT" == "OPTIMLOL_UI_LOCAL" ] ; then
    gulp build-web
    node build/index.js
else
    node --max-old-space-size=410 optimlol_api/server.js
fi